# Generated by Django 3.1.1 on 2020-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_color',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
