# Generated by Django 3.1.1 on 2020-12-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_auto_20201215_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_color', models.CharField(max_length=60)),
                ('text_color', models.CharField(max_length=60)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='forest.page')),
            ],
        ),
    ]
