# Generated by Django 3.1.1 on 2020-12-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0003_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='page',
        ),
    ]
