# Generated by Django 3.1.1 on 2020-12-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0004_remove_color_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='forest.page'),
            preserve_default=False,
        ),
    ]
