# Generated by Django 3.1.1 on 2020-12-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0005_color_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_color',
        ),
    ]
