# Generated by Django 3.1.1 on 2020-12-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0006_remove_page_page_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='page_color',
            new_name='background_color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='page_color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='forest.color'),
        ),
    ]
