# Generated by Django 3.1.1 on 2020-12-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0008_page_page_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='forest.color'),
        ),
    ]
