# Generated by Django 3.1.1 on 2020-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(1, 'Reject'), (2, 'Block'), (3, 'Pending')], default=3),
        ),
    ]
